services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: glassdoor_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - backend_network

  backend:
    image: node:20.16
    container_name: backend_app
    restart: always
    dns:
    - 8.8.8.8
    - 4.4.4.4
    working_dir: /app
    volumes:
      - ./backend:/app
    command: /bin/bash -c "npm install && npm run build && npm run start"
    depends_on:
      - postgres
    environment:
      PORT: 5000
      JWT_SECRET: ProyectoFinalInfraestructuraG50
      DATABASE_URL: postgres://admin:admin_password@postgres:5432/glassdoor_db
    networks:
      - backend_network  

  frontend:
    image: node:20.16
    container_name: frontend_app
    restart: always
    ports:
      - "3000:3000" 
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      API_BASE_URL: http://backend:5000  
      PORT: 3000
      HOST: 0.0.0.0
    depends_on:
      - backend
    command: /bin/bash -c "npm install && npm run build && node dist/server/entry.mjs"
    networks:
      - backend_network 
volumes:
  postgres-data:

networks:
  backend_network:
    driver: bridge  
